name: build and render

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  schedule:
    - cron: "0 0 * * 0"
    # runs on 00:00 every Sunday (UTC)
    # 00:00 UTC = 08:00 Beijing
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-render-release-f64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: clone scene
      run:
        pushd ..;
        git clone https://github.com/w3ntao/pbrt-minus-scenes.git;
        popd;

    - name: cargo build (release, f64 as Float)
      run:
        cargo build --release;

    - name: render
      run:
        bash render_all.sh
