name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --release --verbose

    - name: Download Model Files
      run:
        wget 'https://casual-effects.com/g3d/data10/research/model/dragon/dragon.zip';
        mkdir models;
        unzip dragon.zip -d models/;

    - name: Run Tests
      run: cargo run --release --verbose
